### ISSUE TITLE
App Mercado Pago

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-mercadopago#1]
> Mais um app de pagamento com o padrão `list_payments`, `create_transaction` e notificação de status...

Referências externas:
- https://www.mercadopago.com.br/developers/pt/guides/payments/api/receiving-payment-by-card/
- https://www.mercadopago.com.br/developers/pt/guides/sdks/official/js/

**Comment by leomp12** [comment]
@vitorrgg arruma um ícone pro app também por favor...

**Comment by talissonf** [comment]
v1.0.0 https://github.com/ecomplus/app-mercadopago/compare/ff706a7a0b...e1d2e2adef

**Comment by leomp12** [comment]
@talissonf o [deploy não funciona](https://github.com/ecomplus/app-mercadopago/actions/runs/82522826) por causa disso aqui: https://github.com/ecomplus/app-mercadopago/blob/e1d2e2adefe0b1a3137e3aee50b22e707ebabae8/functions/routes/ecom/modules/create-transaction.js#L1

No deploy `proccess.cwd()` vai ser o root do repo, não o diretório functions, e no Firebase não tenho certeza então acho melhor usar require com path relativo.

**Comment by talissonf** [comment]
> @talissonf o [deploy não funciona](https://github.com/ecomplus/app-mercadopago/actions/runs/82522826) por causa disso aqui:
> 
> https://github.com/ecomplus/app-mercadopago/blob/e1d2e2adefe0b1a3137e3aee50b22e707ebabae8/functions/routes/ecom/modules/create-transaction.js#L1
> 
> No deploy `proccess.cwd()` vai ser o root do repo, não o diretório functions, e no Firebase não tenho certeza então acho melhor usar require com path relativo.

https://github.com/ecomplus/app-mercadopago/commit/f506dfd38e98946b5e5f8fa6d6200de88c34dd51

**Comment by leomp12** [comment]
Segue não conseguindo fazer o deploy, parece que tá dando algum outro erro no código agora.

Isto aqui https://github.com/ecomplus/app-mercadopago/blob/master/functions/lib/new-payment-gateway.js#L8-L12 também não deveria existir, lembra que te falei que estou [minificando os arquivos no deploy](https://github.com/ecomplus/app-mercadopago/blob/master/scripts/firebase-deploy.js#L9)? Você já deveria ler o arquivo minificado, como isto é uma cloud function deixar no source code vai minificar o arquivo em toda requisição, então vai ficar extremamente lento.

**Comment by leomp12** [comment]
Na verdade agora o deploy foi, parece que tinha dado um erro do Firebase mesmo, vou fixar de uma vez essa negócio do onload expression lá pra já importar o arquivo minificado.

@talissonf você já colocou o token do Market nos secrets?
@vitorrgg ainda preciso de ícone e descrição aqui..

**Comment by leomp12** [comment]
@vitorrgg na verdade precisamos de dois ícones, um pro checkout e um pro market

**Comment by talissonf** [comment]
> Segue não conseguindo fazer o deploy, parece que tá dando algum outro erro no código agora.
> 
> Isto aqui https://github.com/ecomplus/app-mercadopago/blob/master/functions/lib/new-payment-gateway.js#L8-L12 também não deveria existir, lembra que te falei que estou [minificando os arquivos no deploy](https://github.com/ecomplus/app-mercadopago/blob/master/scripts/firebase-deploy.js#L9)? Você já deveria ler o arquivo minificado, como isto é uma cloud function deixar no source code vai minificar o arquivo em toda requisição, então vai ficar extremamente lento.

Eu viajei esqueci disso, na verdade como não tinha feito deploy eu deixei do jeito que eu tava testando e nem lembrei disso antes de fazer commit.

**Comment by talissonf** [comment]
> Na verdade agora o deploy foi, parece que tinha dado um erro do Firebase mesmo, vou fixar de uma vez essa negócio do onload expression lá pra já importar o arquivo minificado.
> 
> @talissonf você já colocou o token do Market nos secrets? 
> @vitorrgg ainda preciso de ícone e descrição aqui..

SIM

**Comment by vitorrgg** [comment]
![mp-crédito](https://user-images.githubusercontent.com/35348281/79787962-3f270200-831e-11ea-82a4-a2d50075e2b3.png)
![mercadopago](https://user-images.githubusercontent.com/35348281/79787966-3fbf9880-831e-11ea-8a5f-64f264b624f2.png)

**Comment by leomp12** [comment]
@vitorrgg dá pra fazer um teste em produção por favor? Com cartões inválidos aí se der, tem conta do MP já?
https://app.e-com.plus/#/apps/edit/111223

**Comment by leomp12** [comment]
@matheusgnreis

**Comment by leomp12** [comment]
@vitorrgg o selo pro checkout ficou muito pequeno, dá pra fazer um maior por favor?

**Comment by leomp12** [comment]
@talissonf tá dando pra testar na 1011, o creatre transaction funcionou, mas a notificação não.
Não procurei muito, mas parece que não foi salvo no Firestore (deu um internal error lá) e depois deu um erro quando recebeu a notificação :disappointed:

**Comment by talissonf** [comment]
@leomp12 eu vou tirar o firestore vou utilizar os dados no metadata do payload mesmo, as vezes a notificação acontece e o firestore nem salvou ainda a transação :disappointed:

**Comment by leomp12** [comment]
@talissonf na verdade esse problema da notificação assíncrona aí tá resolvido retornando 503 pro MP pra ele enviar retentativas, só resolver o esquema do get no Firestore mesmo...

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-mercadopago/commit/0ce1ed2277ac50366326c55aa7321b85539971ea
