### ISSUE TITLE
Sugestão de criar opção para que a forma de pagamento do mercado pago seja a primeira a ser mostrada na lista (já aberta)

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/app-mercadopago#22]
**Is your feature request related to a problem? Please describe.**
Hoje o lojista consegue organizar a ordem a ser exibida das formas de pagamento. Ele precisa que a opção do mercado pago, além de ser a primeira na lista, já mostre aberta com as opções.

**Describe the solution you'd like**
Criar opção para mercado pago já vir aberto na tela.

**Additional context**
Sugestão retirada [da comunidade](https://community.e-com.plus/t/exibir-meio-de-pagamento-pre-selecionado/870).

**Comment by leomp12** [comment]
@ThaisChaves na verdade isso seria um enhancement no https://github.com/ecomplus/storefront , não é específico da integração com o MP...
